const productList = [
  {
    id: 1,
    title: "BOXER BIKE",
    pricePerDay: 1500,
    rating: 4.7,
    reviews: 22,
    description: "Strong and fuel-efficient for daily rides.",
    owner: "0761234567",
    image: "/images/rent-bike.webp",
  },
  {
    id: 2,
    title: "FULLFACE HELMET",
    pricePerDay: 500,
    rating: 4.2,
    reviews: 14,
    description: "ISI certified full-face helmet.",
    owner: "0763456789",
    image: "/images/rent-helmet.jpg",
  },
  {
    id: 3,
    title: "BIKE JACKET",
    pricePerDay: 1200,
    rating: 4.5,
    reviews: 31,
    description: "Waterproof and armored jacket.",
    owner: "0765678901",
    image: "/images/rent-jacket.jpg",
  },
  {
    id: 4,
    title: "JBL SPEAKER",
    pricePerDay: 800,
    rating: 4.5,
    reviews: 31,
    description: "JBL CLIP4 original speaker",
    owner: "0714770692",
    image: "/images/rent-jbl.jpeg",
  },
  {
    id: 5,
    title: "ROLEX WRIST WATCH",
    pricePerDay: 1000,
    rating: 4.5,
    reviews: 31,
    description: "Waterproof and branded original watch.",
    owner: "0714770692",
    image: "/images/rent-watch.jpg",
  },
];

export default productList;
